"""add_enrollment_sessions

Revision ID: 0bbdb6b76e88
Revises: 38f5b2d0d868
Create Date: 2026-01-17 14:42:23.278815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbdb6b76e88'
down_revision: Union[str, None] = '38f5b2d0d868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('finger_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('template_data', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_sessions_device_id'), 'enrollment_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_enrollment_sessions_id'), 'enrollment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_sessions_is_deleted'), 'enrollment_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_enrollment_sessions_school_id'), 'enrollment_sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_enrollment_sessions_session_id'), 'enrollment_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_enrollment_sessions_status'), 'enrollment_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_enrollment_sessions_student_id'), 'enrollment_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_sessions_student_id'), table_name='enrollment_sessions')
    op.drop_index(op.f('ix_enrollment_sessions_status'), table_name='enrollment_sessions')
    op.drop_index(op.f('ix_enrollment_sessions_session_id'), table_name='enrollment_sessions')
    op.drop_index(op.f('ix_enrollment_sessions_school_id'), table_name='enrollment_sessions')
    op.drop_index(op.f('ix_enrollment_sessions_is_deleted'), table_name='enrollment_sessions')
    op.drop_index(op.f('ix_enrollment_sessions_id'), table_name='enrollment_sessions')
    op.drop_index(op.f('ix_enrollment_sessions_device_id'), table_name='enrollment_sessions')
    op.drop_table('enrollment_sessions')
    # ### end Alembic commands ###

