"""create_device_groups_table_and_add_foreign_key

Revision ID: 38f5b2d0d868
Revises: d49df1d767f7
Create Date: 2026-01-02 23:19:00.547410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f5b2d0d868'
down_revision: Union[str, None] = 'd49df1d767f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_device_groups_school_name'),
    comment='Device groups for organizing biometric devices'
    )
    op.create_index(op.f('ix_device_groups_id'), 'device_groups', ['id'], unique=False)
    op.create_index(op.f('ix_device_groups_is_deleted'), 'device_groups', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_device_groups_school_id'), 'device_groups', ['school_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'device_groups', ['device_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_device_groups_school_id'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_is_deleted'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_id'), table_name='device_groups')
    op.drop_table('device_groups')
    # ### end Alembic commands ###

