"""add_fingerprint_templates_table

Revision ID: 45c9c2734602
Revises: 8cc22223bb79
Create Date: 2026-02-10 12:53:00.553370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c9c2734602'
down_revision: Union[str, None] = '8cc22223bb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprint_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('finger_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('source_enrollment_session_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['source_enrollment_session_id'], ['enrollment_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Canonical fingerprint template store for transfer/recovery'
    )
    op.create_index(op.f('ix_fingerprint_templates_device_id'), 'fingerprint_templates', ['device_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_templates_finger_id'), 'fingerprint_templates', ['finger_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_templates_id'), 'fingerprint_templates', ['id'], unique=False)
    op.create_index(op.f('ix_fingerprint_templates_is_deleted'), 'fingerprint_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_fingerprint_templates_school_id'), 'fingerprint_templates', ['school_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_templates_source_enrollment_session_id'), 'fingerprint_templates', ['source_enrollment_session_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_templates_student_id'), 'fingerprint_templates', ['student_id'], unique=False)
    # ### end Alembic commands ###

    # Student IDs start at 100 (100, 101, 102, ...). If table already has rows with max(id) >= 100, use max+1.
    op.execute(
        "SELECT setval('students_id_seq', GREATEST(100, COALESCE((SELECT MAX(id) FROM students), 0) + 1))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fingerprint_templates_student_id'), table_name='fingerprint_templates')
    op.drop_index(op.f('ix_fingerprint_templates_source_enrollment_session_id'), table_name='fingerprint_templates')
    op.drop_index(op.f('ix_fingerprint_templates_school_id'), table_name='fingerprint_templates')
    op.drop_index(op.f('ix_fingerprint_templates_is_deleted'), table_name='fingerprint_templates')
    op.drop_index(op.f('ix_fingerprint_templates_id'), table_name='fingerprint_templates')
    op.drop_index(op.f('ix_fingerprint_templates_finger_id'), table_name='fingerprint_templates')
    op.drop_index(op.f('ix_fingerprint_templates_device_id'), table_name='fingerprint_templates')
    op.drop_table('fingerprint_templates')
    # ### end Alembic commands ###
    # Note: students_id_seq is not reverted on downgrade (would require storing previous value).

