"""add_event_type_to_attendance_records

Revision ID: 4d613a69dcd8
Revises: e80f3e08a9c5
Create Date: 2026-02-15 17:34:35.047360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d613a69dcd8'
down_revision: Union[str, None] = 'e80f3e08a9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('event_type', sa.String(length=10), server_default=sa.text("'UNKNOWN'"), nullable=False, comment='IN, OUT, or UNKNOWN'))
    op.create_index(op.f('ix_attendance_records_event_type'), 'attendance_records', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_event_type'), table_name='attendance_records')
    op.drop_column('attendance_records', 'event_type')
    # ### end Alembic commands ###

