"""add_enrollment_composite_index

Revision ID: 8cc22223bb79
Revises: e1a2b3c4d5e6
Create Date: 2026-02-09 13:32:38.039231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc22223bb79'
down_revision: Union[str, None] = 'e1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollment_sessions_student_device_status', table_name='enrollment_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_enrollment_sessions_student_device_status', 'enrollment_sessions', ['student_id', 'device_id', 'status'], unique=False)
    # ### end Alembic commands ###

