"""add_event_type_to_attendance_records

Revision ID: bf860f722ced
Revises: 4d613a69dcd8
Create Date: 2026-02-15 17:41:05.362087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf860f722ced'
down_revision: Union[str, None] = '4d613a69dcd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

