"""add_com_password_to_devices

Revision ID: d49df1d767f7
Revises: b784c49be98b
Create Date: 2026-01-02 22:56:27.620765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from device_service.models import DeviceStatusType

# revision identifiers, used by Alembic.
revision: str = 'd49df1d767f7'
down_revision: Union[str, None] = 'b784c49be98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('com_password', sa.String(length=20), nullable=True))
    op.alter_column('devices', 'status',
               existing_type=postgresql.ENUM('online', 'offline', 'unknown', name='devicestatus'),
               type_=DeviceStatusType(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::devicestatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'status',
               existing_type=DeviceStatusType(length=20),
               type_=postgresql.ENUM('online', 'offline', 'unknown', name='devicestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::devicestatus"))
    op.drop_column('devices', 'com_password')
    # ### end Alembic commands ###

